### PR TITLE
Fix "no module named 'abba_private'"

### PR DESCRIPTION
**Pull request by GuillaumeLeGoc**
Fix https://github.com/BIOP/abba_python/issues/14#issuecomment-2031940552

Still not sure why it didn't work before but at least we'll have a working version for now.

### CODE REVIEW

**Comment by NicoKiaru** [comment]
I'm not sure about the proper fix for that. Did you install the abba-python package or do you work from an IDE ?

Any module / packaging person with a python knowledge is welcomed to help!

**Comment by GuillaumeLeGoc** [comment]
I installed abba-python with `pip install abba-python`.
Before the last update (a little while ago), I could launch the GUI with a Brainglobe atlas.
I tried again today to launch the GUI from a notebook with a Brainglobe atlas and got the error. I tried again from a regular python console and I got the same error. So I went into the `abba.py` file at the designated line, and noticed that here :
https://github.com/BIOP/abba_python/blob/be17a502f4174efcf4622c1418d3d2dacd1aac8b/src/abba_python/abba.py#L101
you import abba_private differently, so I tried to replace the import at the faulty line https://github.com/BIOP/abba_python/blob/be17a502f4174efcf4622c1418d3d2dacd1aac8b/src/abba_python/abba.py#L181 and it worked.

But wth indeed :sweat_smile:

**Comment by NicoKiaru** [comment]
Don't you think it was the correct fix ? Sorry I did not have time to check it yet

**Comment by GuillaumeLeGoc** [comment]
Oops. I didn't know PRs were directly linked to the fork. I deleted the latter to re-fork it and start what I did from scratch... I'll try to redo the PR and find a way to work on another version (I guess this is the purpose of branches, I need to find out about that) 😓

**Pull request closed without merging**
